### ISSUE TITLE
Possibly wrong usage of atomic-box-set!

### ISSUE THREAD

**Issue by cireu** [wingo/fibers#48]
https://github.com/wingo/fibers/blob/master/fibers/scheduler.scm#L272

I see `(atomic-box-set! box (+ (atomic-box-ref ...) ...))` pattern here, but IIUC this will cause race condition in multithreading context, the box maybe update after `atomic-box-ref` and before `atomic-box-set!` by other threads.

I think this implementation is correct

```scheme
(define update-count-box (box)
  (let retry ((old-box-val (atomic-box-ref box)))
    (let ((new-val (logand (1+ old-box-val) #xffffFFFF))
          (cur-box-val (atomic-box-compare-and-swap! box old-box-val new-val)))
      (if (eq? cur-box-val new-val)
          new-val
          (retry cur-box-val)))))
```

**Comment by emixa-d** [comment]
That's incorrect, you are using Lisp's `defun` instead of Scheme's `define`.

I think the old implementation is correct, because there is no multithreading here -- IIUC, the only thread modifying the scheduler's runcount box is the scheduler thread.

I'll need to look more carefully to verify this, but I think the bug here is a missing comment explaining this.
